heat_template_version: 2015-04-30
description: CPU intensive resource.

parameters:
  availability_zone:
    type: string
    description: The Availability Zone to launch the instance.
  volume_size:
    type: number
    description: Size of the volume to be created.
  image_id:
    type: string
    label: Image ID
    description: Image to be used for compute instance
    constraints:
      - custom_constraint: glance.image
  instance_type:
    type: string
    label: Instance Type
    description: Type of instance (flavor) to be used
    constraints:
      - custom_constraint: nova.flavor
  network_id:
    type: string
    label: Network ID/Name
    description: Network to be used for compute instance.
  key:
    type: string
    description: Key pair used to ssh into instance.
  volume_size:
    type: number
    description: Size of the volume to be created.
    default: 1
    constraints:
      - range: { min: 1 }
resources:
