heat_template_version: 2014-10-16
description: Disk intensive resource.

parameters:
  availability_zone:
    type: string
    description: The Availability Zone to launch the instance.
    default: nova
  volume_size:
    type: number
    description: Size of the volume to be created.
    default: 1
    constraints:
      - range: { min: 1 }
  image_id:
    type: string
    label: Image ID
    description: Image to be used for compute instance
    default: 80245de9-cb3c-4f61-ac84-e0f800055cf5
  instance_type:
    type: string
    label: Instance Type
    description: Type of instance (flavor) to be used
    default: m1.tiny
resources:
  nova_server:
    type: OS::Nova::Server
    properties:
      name: disk-%index%
      availability_zone: { get_param: availability_zone }
      image: { get_param: image_id }
      flavor: { get_param: instance_type }
  cinder_volume:
    type: OS::Cinder::Volume
    properties:
      size: { get_param: volume_size }
      availability_zone: { get_param: availability_zone }
  volume_attachment:
    type: OS::Cinder::VolumeAttachment
    properties:
      volume_id: { get_resource: cinder_volume }
      instance_uuid: { get_resource: nova_server }
      mountpoint: /dev/vdc
