heat_template_version: 2015-04-30
description: Disk intensive resource.

parameters:
  availability_zone:
    type: string
    description: The Availability Zone to launch the instance.
  key:
    type: string
    description: Key pair used to ssh into instance.
  volume_size:
    type: number
    description: Size of the volume to be created.
    default: 1
    constraints:
      - range: { min: 1 }
  image_id:
    type: string
    label: Image ID
    description: Image to be used for compute instance
    constraints:
      - custom_constraint: glance.image
  instance_type:
    type: string
    label: Instance Type
    description: Type of instance (flavor) to be used
    constraints:
      - custom_constraint: nova.flavor
  network_id:
    type: string
    label: Network ID/Name
    description: Network to be used for compute instance.
resources:
  name_nonce:
    type: OS::Heat::RandomString
    properties:
            length: 7
            sequence: lowercase
  nova_server:
    type: OS::Nova::Server
    properties:
      name:
        str_replace:
          template: disk-$NONCE
          params:
            $NONCE: { get_resource: name_nonce}
      availability_zone: { get_param: availability_zone }
      key_name: { get_param: key }
      networks:
        - network: { get_param: network_id }
      image: { get_param: image_id }
      flavor: { get_param: instance_type }
      user_data_format: RAW
      user_data: |
        #!/bin/sh
        sudo stress-ng --hdd 60 --hdd-bytes 1g --metrics-brief
  cinder_volume:
    type: OS::Cinder::Volume
    properties:
      size: { get_param: volume_size }
      availability_zone: { get_param: availability_zone }
  volume_attachment:
    type: OS::Cinder::VolumeAttachment
    properties:
      volume_id: { get_resource: cinder_volume }
      instance_uuid: { get_resource: nova_server }
      mountpoint: /dev/vdc
