heat_template_version: 2015-04-30
description: Network intensive resource.

parameters:
  availability_zone:
    type: string
    description: The Availability Zone to launch the instance.
  key:
    type: string
    description: Key pair used to ssh into instance.
  image_id:
    type: string
    label: Image ID
    description: Image to be used for compute instance
    constraints:
      - custom_constraint: glance.image
  instance_type:
    type: string
    label: Instance Type
    description: Type of instance (flavor) to be used
    constraints:
      - custom_constraint: nova.flavor
  client_ip:
    type: string
    label: Client IP
    description: IP of netcat client
  network_id:
    type: string
    label: Network ID/Name
    description: Network to be used for compute instance.
resources:
  security_group:
      type: OS::Neutron::SecurityGroup
      properties:
        name: web_server_security_group
        rules:
          - protocol: tcp
            port_range_min: 1234
            port_range_max: 1234
          - protocol: tcp
            port_range_min: 22
            port_range_max: 22
  port_server:
    type: OS::Neutron::Port
    properties:
      network: { get_param: network_id }
      security_groups:
        - { get_resource: security_group }
  name_nonce:
    type: OS::Heat::RandomString
    properties:
            length: 7
            sequence: lowercase
  nova_server:
    type: OS::Nova::Server
    properties:
      name:
        str_replace:
          template: network-server-$NONCE
          params:
            $NONCE: { get_resource: name_nonce}
      availability_zone: { get_param: availability_zone }
      image: { get_param: image_id }
      flavor: { get_param: instance_type }
      key_name: { get_param: key }
      networks: 
        - port: { get_resource: port_server }
      user_data_format: RAW
      user_data: 
        str_replace:
          params:
            __client_ip__: { get_param: client_ip }
          template: |
            #!/bin/sh
            sudo apt-get update
            sudo apt-get upgrade
            sudo apt-get install -y nc
            for i in {2..10}
            do
               dd if=/dev/urandom of=random.img count=$i bs=10M
               nc -w 10 '__client_ip__' 1234 < random.img
               rm random.img
            done
outputs:
  ip:
    description: The ip address of the mysql instance
    value: { get_attr: [nova_server, first_address] }
