heat_template_version: 2015-04-30
description: Network intensive resource.

parameters:
  availability_zone:
    type: string
    description: The Availability Zone to launch the instance.
  key:
    type: string
    description: Key pair used to ssh into instance.
  image_id:
    type: string
    label: Image ID
    description: Image to be used for compute instance
    constraints:
      - custom_constraint: glance.image
  instance_type:
    type: string
    label: Instance Type
    description: Type of instance (flavor) to be used
    constraints:
      - custom_constraint: nova.flavor
  network_id:
    type: string
    label: Network ID/Name
    description: Network to be used for compute instance.
resources:
  security_group:
      type: OS::Neutron::SecurityGroup
      properties:
        name: web_server_security_group
        rules:
          - protocol: tcp
            port_range_min: 1234
            port_range_max: 1234
          - protocol: tcp
            port_range_min: 1235
            port_range_max: 1235
          - protocol: tcp
            port_range_min: 22
            port_range_max: 22
  port_client:
    type: OS::Neutron::Port
    properties:
      network: { get_param: network_id }
      security_groups:
        - { get_resource: security_group }
  name_nonce:
    type: OS::Heat::RandomString
    properties:
            length: 7
            sequence: lowercase
  nova_client:
    type: OS::Nova::Server
    properties:
      name:
        str_replace:
          template: network-client-$NONCE
          params:
            $NONCE: { get_resource: name_nonce}
      availability_zone: { get_param: availability_zone }
      image: { get_param: image_id }
      flavor: { get_param: instance_type }
      key_name: { get_param: key }
      networks: 
        - port: { get_resource: port_client }
      user_data_format: RAW
      user_data: |
        #!/bin/sh
        while [1]; do
           echo "Stressing script started..."
           sudo nc -l -p 1234 > /root/out_small.file
           sudo nc -l -p 1235 > /root/out_large.file
           sudo rm /root/out.file /root/out_large.file
        done
outputs:
  ip:
    description: The ip address of the mysql instance
    value: { get_attr: [nova_client, first_address] }
