heat_template_version: 2015-04-30
description: Network intensive resource.

parameters:
  availability_zone:
    type: string
    description: The Availability Zone to launch the instance.
  key_name:
    type: string
    description: Key pair used to ssh into instance.
  image:
    type: string
    label: Image ID
    description: Image to be used for compute instance
    constraints:
      - custom_constraint: glance.image
  flavor:
    type: string
    label: Instance Type
    description: Type of instance (flavor) to be used
    constraints:
      - custom_constraint: nova.flavor
  network:
    type: string
    label: Network ID/Name
    description: Network to be used for compute instance.
  size:
    type: number
    description: Size of the volume to be created.
    default: 1
    constraints:
      - range: { min: 1 }
resources:
  security_group:
      type: OS::Neutron::SecurityGroup
      properties:
        name: web_server_security_group
        rules:
          - protocol: tcp
            port_range_min: 1234
            port_range_max: 1234
          - protocol: tcp
            port_range_min: 1235
            port_range_max: 1235
          - protocol: tcp
            port_range_min: 22
            port_range_max: 22
  port_client:
    type: OS::Neutron::Port
    properties:
      network: { get_param: network }
      security_groups:
        - { get_resource: security_group }
  name_nonce:
    type: OS::Heat::RandomString
    properties:
            length: 7
            sequence: lowercase
  nova_client:
    type: OS::Nova::Server
    properties:
      name:
        str_replace:
          template: network-client-$NONCE
          params:
            $NONCE: { get_resource: name_nonce}
      availability_zone: { get_param: availability_zone }
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      networks: 
        - port: { get_resource: port_client }
      user_data_format: RAW
      user_data: |
        #!/bin/sh
        sudo sed -i '1s/^/nameserver 8.8.8.8 /' /etc/resolv.conf
        sudo apt-get update
        while [1]; do
           echo "Stressing script started..."
           sudo nc -l -p 1234 > /root/out_small.file
           sudo nc -l -p 1235 > /root/out_large.file
           sudo rm /root/out.file /root/out_large.file
        done
  port_server:
    type: OS::Neutron::Port
    properties:
      network: { get_param: network }
      security_groups:
        - { get_resource: security_group }
  nova_server:
    type: OS::Nova::Server
    properties:
      name:
        str_replace:
          template: network-server-$NONCE
          params:
            $NONCE: { get_resource: name_nonce}
      availability_zone: { get_param: availability_zone }
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      networks: 
        - port: { get_resource: port_server }
      user_data_format: RAW
      user_data: 
        str_replace:
          params:
            __client_ip__: { get_attr: [nova_client,first_address]  }
          template: |
            #!/bin/sh
            sed -i '1s/^/nameserver 8.8.8.8 /' /etc/resolv.conf
            sudo apt-get -y update
            sudo apt-get -y install git
            wget https://dl.influxdata.com/telegraf/releases/telegraf_1.0.1_amd64.deb
            sudo dpkg -i telegraf_1.0.1_amd64.deb
            sudo apt-get install -f
            telegraf config > /etc/telegraf/telegraf.conf
            sed -i -e "s/localhost/__influx_ip__/g" /etc/telegraf/telegraf.conf
            service telegraf restart
            sudo sed -i '1s/^/nameserver 8.8.8.8 /' /etc/resolv.conf
            sudo apt-get update
            echo '__client_ip' > /root/ip
            dd if=/dev/urandom of=random_small.img count=10 bs=10M
            dd if=/dev/urandom of=random_large.img count=100 bs=10M
            while [1]; do
                nc -w 10 '__client_ip__' 1234 < random_small.img
                nc -w 10 '__client_ip__' 1235 < random_large.img
            done
