heat_template_version: 2013-05-23

description: |
 The heat template is used to demo the 'console_urls' attribute
 of OS::Nova::Server.
parameters:
 image:
   type: string
   default: ubuntu.medium
 flavor:
   type: string
   default: large
 network_id:
   type: string
   default: 44b0bffa-cb5f-44f9-ba3e-d371a4149624

resources:
 my_key:
   type: OS::Nova::KeyPair
   properties:
     save_private_key: true
     name: my_key
 server:
   type: OS::Nova::Server
   properties:
     image: { get_param: image }
     flavor: { get_param: flavor }
     networks:
        - network: { get_param: network_id }
     key_name: test
     user_data_format: RAW
     user_data:
       str_replace:
         params:
           __image__: { get_param: image }
           __flavor__: { get_param: flavor }
           __network__: { get_param: network_id }
         template: |
           #!/bin/sh
           export OS_AUTH_URL=https://cloud1.osic.org:5000/v3
           export OS_TENANT_ID=ddd81f9ab03f45e09196169abceaec6f
           export OS_TENANT_NAME="osic-engineering"
           export OS_USER_DOMAIN_NAME="Default"
           export OS_USERNAME="nish.patwa"
           export OS_PASSWORD="N1shp@twa1"
           export OS_REGION_NAME="RegionOne"
           export OS_ENDPOINT_TYPE=publicURL
           export OS_INTERFACE=public
           export OS_IDENTITY_API_VERSION=3
           sed -i '1s/^/nameserver 8.8.8.8 /' /etc/resolv.conf
           sudo apt-get -y dist-upgrade
           sudo apt-get -y update
           sudo apt-get -y install git
           sudo apt-get -y install python
           sudo apt-get -y install python-pip
           git clone https://github.com/GoogleCloudPlatform/PerfKitBenchmarker.git
           sudo pip install -r PerfKitBenchmarker/perfkitbenchmarker/providers/openstack/requirements.txt
           ./PerfKitBenchmarker/pkb.py --cloud=OpenStack --image='__image__' --openstack_image_username=ubuntu --openstack_network='__network__' --benchmarks=ping --os_type=debian --openstack_volume_size=1 --machine_type='__flavor__' --run_stage=provision
outputs:
 single_console_type:
   value: { get_attr: server, console_urls, novnc }
   description: console URL for the server (novnc in this case)
 all_console_urls:
   value: { get_attr: [server, console_urls] }
   description: all available console URLs for the server
 private_key:
   description: Private key
   value: { get_attr: [ my_key, private_key ] }
