heat_template_version: 2015-04-30
description: Perfkit workload

parameters:
  availability_zone:
    type: string
    description: The Availability Zone to launch the instance.
  volume_size:
    type: number
    description: Size of the volume to be created.
  image_id:
    type: string
    label: Image ID
    description: Image to be used for compute instance
    constraints:
      - custom_constraint: glance.image
  instance_type:
    type: string
    label: Instance Type
    description: Type of instance (flavor) to be used
    constraints:
      - custom_constraint: nova.flavor
  network_id:
    type: string
    label: Network ID/Name
    description: Network to be used for compute instance.
  key:
    type: string
    description: Key pair used to ssh into instance.
resources:
  name_nonce:
    type: OS::Heat::RandomString
    properties:
            length: 7
            sequence: lowercase
  nova_server:
    type: OS::Nova::Server
    properties:
      name:
        str_replace:
          template: perfkit-$NONCE
          params:
            $NONCE: { get_resource: name_nonce}
      availability_zone: { get_param: availability_zone }
      image: { get_param: image_id }
      flavor: { get_param: instance_type }
      key_name: { get_param: key }
      networks: 
        - network: { get_param: network_id }
      user_data_format: RAW
      user_data: |
        #!/bin/sh
        export LC_ALL=C
        export CINDER_ENDPOINT_TYPE=internalURL
        export NOVA_ENDPOINT_TYPE=internalURL
        export OS_ENDPOINT_TYPE=internalURL
        export OS_INTERFACE=internalURL
        export OS_USERNAME=admin
        export OS_PASSWORD=openstack
        export OS_PROJECT_NAME=admin
        export OS_TENANT_NAME=admin
        export OS_AUTH_URL=http://172.29.236.100:5000/v3
        export OS_NO_CACHE=1
        export OS_USER_DOMAIN_NAME=Default
        export OS_PROJECT_DOMAIN_NAME=Default
        export OS_REGION_NAME=RegionOne
        export OS_IDENTITY_API_VERSION=3
        export OS_AUTH_VERSION=3
        sed -i '1s/^/nameserver 8.8.8.8 /' /etc/resolv.conf
        sudo apt-get udpate
        sudo apt-get -y install git
        sudo apt-get -y install python
        sudo apt-get -y install python-pip
        git clone https://github.com/GoogleCloudPlatform/PerfKitBenchmarker.git
        sudo pip install -r PerfKitBenchmarker/perfkitbenchmarker/providers/openstack/requirements.txt
        ./PerfKitBenchmarker/pkb.py --cloud=OpenStack --image='__image__' --openstack_image_username=ubuntu --openstack_network='__network__' --benchmarks=ping --os_type=debian --openstack_volume_size=1 --machine_type='__flavor__' --run_stage=provision
outputs: 
  host: 
    description: The host this server lives on. 
    value: {get_attr: [nova_server, show, 'OS-EXT-SRV-ATTR:host']} 
