heat_template_version: 2015-04-30
description: RAM intensive resource.

parameters:
  availability_zone:
    type: string
    description: The Availability Zone to launch the instance.
  key:
    type: string
    description: Key pair used to ssh into instance.
  image_id:
    type: string
    label: Image ID
    description: Image to be used for compute instance
    constraints:
      - custom_constraint: glance.image
  instance_type:
    type: string
    label: Instance Type
    description: Type of instance (flavor) to be used
    constraints:
      - custom_constraint: nova.flavor
  network_id:
    type: string
    label: Network ID/Name
    description: Network to be used for compute instance.
  volume_size:
    type: number
    description: Size of the volume to be created.
    default: 1
    constraints:
      - range: { min: 1 }
resources:
  name_nonce:
    type: OS::Heat::RandomString
    properties:
            length: 7
            sequence: lowercase
  nova_server:
    type: OS::Nova::Server
    properties:
      name:
        str_replace:
          template: ram-$NONCE
          params:
            $NONCE: { get_resource: name_nonce}
      availability_zone: { get_param: availability_zone }
      image: { get_param: image_id }
      networks:
        - network: { get_param: network_id }
      flavor: { get_param: instance_type }
      key_name: { get_param: key }
      user_data_format: RAW
      user_data: |
        #!/bin/sh -x
        sudo apt-get install -y stress-ng
        sudo stress-ng -m 55 --vm-bytes 500m --metrics-brief
