heat_template_version: 2015-04-30
description: CPU intensive resource.

parameters:
  availability_zone:
    type: string
    description: The Availability Zone to launch the instance.
  volume_size:
    type: number
    description: Size of the volume to be created.
  image_id:
    type: string
    label: Image ID
    description: Image to be used for compute instance
    constraints:
      - custom_constraint: glance.image
  key:
    type: string
    description: Key pair used to ssh into instance.
  instance_type:
    type: string
    label: Flavor Type
    description: Flavor Type
    constraints:
      - custom_constraint: nova.flavor
  network_id:
    type: string
    label: Network ID/Name
    description: Network to be used for compute instance.
resources:
  nova_server_disk:
    type: disk.yaml
    properties:
      image_id: { get_param: image_id }
      instance_type: { get_param: instance_type }
      network_id: { get_param: network_id }
      availability_zone: { get_param: availability_zone }
      volume_size: { get_param: volume_size }
      key: { get_param: key }
  nova_server_cpu:
    type: cpu.yaml
    properties:
      image_id: { get_param: image_id }
      instance_type: { get_param: instance_type }
      network_id: { get_param: network_id }
      availability_zone: { get_param: availability_zone }
      volume_size: { get_param: volume_size }
      key: { get_param: key }
  nova_server_ram:
    type: ram.yaml
    properties:
      image_id: { get_param: image_id }
      instance_type: { get_param: instance_type }
      network_id: { get_param: network_id }
      availability_zone: { get_param: availability_zone }
      key: { get_param: key }
  #nova_client_nw:
  #  type: net-client.yaml
  #  properties:
   #   image_id: { get_param: image_id }
   #   instance_type: { get_param: instance_type }
   #   network_id: { get_param: network_id }
   #   availability_zone: { get_param: availability_zone }
   #   key: { get_param: key }
 # nova_server_nw:
  #  type: net-server.yaml
   # properties:
    #  image_id: { get_param: image_id }
     # instance_type: { get_param: instance_type }
      #network_id: { get_param: network_id }
      #availability_zone: { get_param: availability_zone }
      #key: { get_param: key }
      #client_ip: {get_attr: [nova_client_nw, ip]}
