heat_template_version: 2013-05-23

description: |
 The heat template is used to demo the 'console_urls' attribute
 of OS::Nova::Server.
parameters:
 image:
   type: string
   default: ubuntu.medium
 flavor:
   type: string
   default: large
 network_id:
   type: string
   default: 44b0bffa-cb5f-44f9-ba3e-d371a4149624

resources:
 server:
   type: OS::Nova::Server
   properties:
     image: { get_param: image }
     flavor: { get_param: flavor }
     networks:
        - network: { get_param: network_id }
     user_data_format: RAW
     user_data: |
       #!/bin/sh
       sudo apt-get update
       sudo apt-get install git
       wget https://dl.influxdata.com/telegraf/releases/telegraf_1.0.1_amd64.deb
       sudo dpkg -i telegraf_1.0.1_amd64.deb
       sudo apt-get install -f
       telegraf config > /etc/telegraf/telegraf.conf
       sed -i -e 's/localhost/172.29.237.246/g' /etc/telegraf/telegraf.conf
       cat /etc/telegraf/telegraf.conf
       service telegraf restart
       tail -f /var/log/telegraf/telegraf.log

outputs:
 single_console_type:
   value: { get_attr: server, console_urls, novnc }
   description: console URL for the server (novnc in this case)
 all_console_urls:
   value: { get_attr: [server, console_urls] }
   description: all available console URLs for the server
