description: A sample slice.
heat_template_version: 2015-04-30
parameters:
  availability_zone:
    description: The Availability Zone to launch the instance.
    type: string
  flavor:
    constraints:
    - custom_constraint: nova.flavor
    description: Type of instance (flavor) to be used
    label: Instance Type
    type: string
  image:
    constraints:
    - custom_constraint: glance.image
    description: Image to be used for compute instance
    label: Image ID
    type: string
  influx_ip:
    description: Ip address of the database of monitoring stack
    type: string
  key_name:
    description: Key pair used to ssh into instance.
    type: string
  network:
    description: Network to be used for compute instance.
    label: Network ID/Name
    type: string
  size:
    constraints:
    - range:
        min: 1
    default: 1
    description: Size of the volume to be created.
    type: number
resources:
  ram-R2AZ2:
    properties:
      availability_zone:
        get_param: availability_zone
      flavor:
        get_param: flavor
      image:
        get_param: image
      influx_ip:
        get_param: influx_ip
      key_name:
        get_param: key_name
      network:
        get_param: network
    type: /opt/ops-workload-framework/heat_workload/resource_definition/ram.yaml
