heat_template_version: 2015-04-30
description: A sample slice.

parameters:
  availability_zone:
    type: string
    description: The Availability Zone to launch the instance.
  size:
    type: number
    description: Size of the volume to be created.
  image:
    type: string
    label: Image ID
    description: Image to be used for compute instance
    constraints:
      - custom_constraint: glance.image
  flavor:
    type: string
    label: Instance Type
    description: Type of instance (flavor) to be used
    constraints:
      - custom_constraint: nova.flavor
  network:
    type: string
    label: Network ID/Name
    description: Network to be used for compute instance.
  key_name:
    type: string
    description: Key pair used to ssh into instance.
  size:
    type: number
    description: Size of the volume to be created.
    default: 1
    constraints:
      - range: { min: 1 }
  influx_ip:
    type: string
    description: Ip address of the database of monitoring stack
resources:
  cpu-ND58V: 
    type: /opt/ops-workload-framework/heat_workload/resource_definition/cpu.yaml 
    properties: 
      availability_zone: { get_param: availability_zone }
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      network: { get_param: network }
      influx_ip: { get_param: influx_ip }
  ram-5GVW0: 
    type: /opt/ops-workload-framework/heat_workload/resource_definition/ram.yaml 
    properties: 
      availability_zone: { get_param: availability_zone }
      image: { get_param: image }
      network: { get_param: network }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      influx_ip: { get_param: influx_ip }
