heat_template_version: 2015-04-30
description: Template to deploy a slice of instances with parameters.

parameters:
  availability_zone:
    type: string
    description: The Availability Zone to launch the instance.
  key:
    type: string
    description: Key pair used to ssh into instance.
  volume_size:
    type: number
    description: Size of the volume to be created.
    default: 1
  image_id:
    type: string
    label: Image ID
    description: Image to be used for compute instance
  instance_type:
    type: string
    label: Instance Type
    description: Type of instance (flavor) to be used
  num_of_slices:
    type: number
    label: Number of Slices
    description: Number of Slices to be deployed
    constraints:
      - range: {min: 1}
  scaling_size:
    type: number
    label: Scaling factor
    description: Maximum value of scaling factor
    constraints:
      - range: {min: 1}
  network_id:
    type: string
    label: Network ID or name
resources:
  group-small:
    type: OS::Heat::AutoScalingGroup
    properties:
      cooldown: 
      desired_capacity: { get_param: num_of_slices }
      max_size: 99
      min_size: 1
      resource:
        type: OS::Nova::Server::Disk
        properties:
          image_id: { get_param: image_id }
          instance_type: { get_param: instance_type }
          network_id: { get_param: network_id }
          availability_zone: { get_param: availability_zone }
          volume_size: { get_param: volume_size }
          key: { get_param: key }
  scaleup_policy_small:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: { get_resource: group-small }
      #cooldown: 10
      scaling_adjustment: { get_param: scaling_size }

outputs:
  scale_up_url_small:
    description: >
      This URL is the webhook to scale up the autoscaling group.  You
      can invoke the scale-up operation by doing an HTTP POST to this
      URL; no body nor extra headers are needed.
    value: {get_attr: [scaleup_policy_small, alarm_url]}
