heat_template_version: 2013-05-23
description: Template to deploy a slice of instances with parameters.

parameters:
  num_of_slices:
    type: number
    label: Number of Slices
    description: Number of Slices to be deployed
    default: 1
    constraints:
      - range: {min: 1}
  scaling_size:
    type: number
    label: Scaling factor
    description: Maximum value of scaling factor
    default: 1
    constraints:
      - range: {min: 1}
resources:
  group-disk:
    type: OS::Heat::AutoScalingGroup
    properties:
      cooldown: 60
      desired_capacity: { get_param: num_of_slices }
      max_size: { get_param: scaling_size }
      min_size: 1
      resource:
        type: OS::Nova::Server::Disk
  group-cpu:
    type: OS::Heat::AutoScalingGroup
    properties:
      cooldown: 60
      desired_capacity: { get_param: num_of_slices }
      max_size: { get_param: scaling_size }
      min_size: 1
      resource:
        type: OS::Nova::Server::Cpu
  group-ram:
    type: OS::Heat::AutoScalingGroup
    properties:
      cooldown: 60
      desired_capacity: { get_param: num_of_slices }
      max_size: { get_param: scaling_size }
      min_size: 1
      resource:
        type: OS::Nova::Server::Ram
  scaleup_policy_disk:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: { get_resource: group-disk }
      cooldown: 60
      scaling_adjustment: 1 
  scaleup_policy_cpu:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: { get_resource: group-cpu }
      cooldown: 60
      scaling_adjustment: 1   
  scaleup_policy_ram:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: { get_resource: group-ram }
      cooldown: 60
      scaling_adjustment: 1
  cpu_alarm_high:
    type: OS::Ceilometer::Alarm
    properties:
      description: Scale-up the slice if the average CPU > 50% for 1 minute
      meter_name: cpu_util
      statistic: avg
      period: 60
      evaluation_periods: 1
      threshold: 50
      alarm_actions:
        - {get_attr: [scaleup_policy_cpu, alarm_url]}
      comparison_operator: gt
